### ISSUE TITLE
unable to display some symbols and characters in bgpmap

### ISSUE THREAD

**Issue by SerinaNya** [xddxdd/bird-lg-go#105]
Here's some thing wrong in bgpmap.

The origin text in whois response is `xxx & Internal 中文`.

<details>

![image](https://github.com/xddxdd/bird-lg-go/assets/34389622/46d10a4f-e741-4bfa-a9e7-9f4355fe2fe1)

</details>

![image](https://github.com/xddxdd/bird-lg-go/assets/34389622/cc557b2e-4136-4de9-a782-4cbdc21fe79b)

Here's the SVG element, I take this screenshot from Chrome Devtool.

![image](https://github.com/xddxdd/bird-lg-go/assets/34389622/5dc1ef58-caba-44e1-a778-22db9ea81492)

Can bird-lg-go support these characters in bgpmap?

**Comment by xddxdd** [comment]
Can you try the latest commit? I fixed an issue with browsers not properly decoding UTF-8 Base64 strings.

**Comment by SerinaNya** [comment]
> Can you try the latest commit? I fixed an issue with browsers not properly decoding UTF-8 Base64 strings.

I have tried https://github.com/xddxdd/bird-lg-go/commit/f0f072c4a698236af3e76ec34436175e208ff3d1 .

`中文` works now, `&` still doesn't work.

![image](https://github.com/xddxdd/bird-lg-go/assets/34389622/6a1fcd5b-a196-4c2b-bbed-54b9b797d1eb)

**Comment by xddxdd** [comment]
Just pushed another update, can you try again? Symbols like `<`, `>`, `&` should be fixed now.

**Comment by SerinaNya** [comment]
> Just pushed another update, can you try again? Symbols like `<`, `>`, `&` should be fixed now.

https://github.com/xddxdd/bird-lg-go/commit/0dd1c07b661cca51482eae3b219699e443473b2f works.

**Comment by xddxdd** [comment]
Thanks for confirming, I will create a new release shortly.
